# Autogenerated wrapper script for ProtocolBuffersCompiler_jll for i686-w64-mingw32-cxx11
export binary_symbol, libprotobuf, libprotoc

using CompilerSupportLibraries_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ProtocolBuffersCompiler")
JLLWrappers.@declare_library_product(libprotobuf, "libprotobuf.dll")
JLLWrappers.@declare_library_product(libprotoc, "libprotoc.dll")
JLLWrappers.@declare_executable_product(binary_symbol)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libprotobuf,
        "bin\\libprotobuf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprotoc,
        "bin\\libprotoc.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        binary_symbol,
        "bin\\protoc.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
