# Autogenerated wrapper script for ProtocolBuffersCompiler_jll for x86_64-apple-darwin
export libprotobuf, libprotoc, protoc

using CompilerSupportLibraries_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ProtocolBuffersCompiler")
JLLWrappers.@declare_library_product(libprotobuf, "@rpath/libprotobuf.3.16.0.0.dylib")
JLLWrappers.@declare_library_product(libprotoc, "@rpath/libprotoc.3.16.0.0.dylib")
JLLWrappers.@declare_executable_product(protoc)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libprotobuf,
        "lib/libprotobuf.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprotoc,
        "lib/libprotoc.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        protoc,
        "bin/protoc",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
